### ISSUE TITLE
玩客云真机测试过吗

### ISSUE THREAD

**Issue by wwhai** [TooYoungTooSimp/s805-armbian-build#10]
大佬在玩客云真机测试过吗？

**Comment by TooYoungTooSimp** [comment]
> 大佬在玩客云真机测试过吗？

有真机，但暂时不在身边没有刷入进行测试，慎用

**Comment by wwhai** [comment]
> > 大佬在玩客云真机测试过吗？
> 
> 有真机，但暂时不在身边没有刷入进行测试，慎用

谢谢
